### ISSUE TITLE
Welcome new PRs?

### ISSUE THREAD

**Issue by FragmentedPacket** [nleiva/terraform-provider-nautobot#53]
I'm looking to automate some of my home lab with Terraform, but want to use Nautobot Virtual Machines as a data source. Would you be open to a PR for this new data source?

**Comment by nleiva** [comment]
Sure, let me take a look. Thanks!

**Comment by FragmentedPacket** [comment]
Thank you. I will create another PR eventually to create a data resource for the GraphQL api as flexible data source.

**Comment by nleiva** [comment]
Sounds good, thank you very much for bringing this back to life.
